# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba41d3305bc44456e1a5ba03f9057e92a6b19e9fff3d983a98cef8c87ad5f72935320bb02c3d20718a21de799e6a667bb75a5074dc7f9e5a93fc9c2c3bfc6e11

test:
  secret_key_base: cb1b47d6df3ca27dbef9566056ba8317f1142775efbd6a06c52b3aec2d4a059de07284b958258df0ce4c8eceee6dcf1fdf6484dbbb9fea29f79b3af972f570f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
